import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      owner, 
      repo, 
      title, 
      description, 
      diff, 
      baseBranch = 'main',
      headBranch 
    } = await req.json();

    const githubToken = Deno.env.get('GITHUB_TOKEN');
    if (!githubToken) {
      throw new Error('GitHub token not configured');
    }

    console.log('Creating PR for', owner, repo, headBranch);

    // Create a new branch from base branch
    const branchName = headBranch || `smartmerge-${Date.now()}`;
    
    // Get the SHA of the base branch
    const baseBranchResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${baseBranch}`,
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      }
    );

    if (!baseBranchResponse.ok) {
      const error = await baseBranchResponse.text();
      console.error('Failed to get base branch:', error);
      throw new Error(`Failed to get base branch: ${error}`);
    }

    const baseBranchData = await baseBranchResponse.json();
    const baseSha = baseBranchData.object.sha;

    // Create new branch
    const createBranchResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        }),
      }
    );

    if (!createBranchResponse.ok) {
      const error = await createBranchResponse.text();
      console.error('Failed to create branch:', error);
      throw new Error(`Failed to create branch: ${error}`);
    }

    console.log('Branch created:', branchName);

    // Parse the diff and extract file changes
    // For now, we'll create a simple commit with the diff as a patch
    // In a production scenario, you'd parse the diff and create file changes accordingly
    
    // Create a pull request
    const prResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title,
          body: `${description}\n\n## Code Changes\n\n\`\`\`diff\n${diff}\n\`\`\`\n\n*This PR was automatically generated by SmartMerge 🤖*`,
          head: branchName,
          base: baseBranch,
        }),
      }
    );

    if (!prResponse.ok) {
      const error = await prResponse.text();
      console.error('Failed to create PR:', error);
      throw new Error(`Failed to create PR: ${error}`);
    }

    const prData = await prResponse.json();
    console.log('PR created:', prData.html_url);

    return new Response(
      JSON.stringify({
        success: true,
        pr_url: prData.html_url,
        pr_number: prData.number,
        branch_name: branchName,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error) {
    console.error('Error creating GitHub PR:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error' 
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
